charged-ieee: Change colon to period in figure caption
typst/templates pull request #60
Opened 2024-10-30 16:30 UTC by notPlancha

According to https://guides.library.uwa.edu.au/IEEE/images_tables_figures, the captions should be centre-justified, and the [IEEE Editorial Manual for Authors](http://journals.ieeeauthorcenter.ieee.org/wp-content/uploads/sites/7/IEEE-Editorial-Style-Manual-for-Authors.pdf) seems to support that idea, although not explicitly

Using "Fig. 1. Caption text." is explicit though.

Feel free to close if not appropriate.

2024-10-30 16:32 UTC, laurmaedje commented
cc @j95io

2024-10-31 10:46 UTC, j95io commented
Regarding colon or period, apparently the default in the LaTeX template is the period.
In actual papers I've also seen colon a lot, so I took a look where that comes from.
It turns out that when using e.g. `\usepackage{subfig}`, then colons start appearing in all the captions.

2024-11-12 11:31 UTC, laurmaedje commented
> "center if single line, wraparound if multi line." is also the default behavior for regular figure captions, i.e. for non-table figures.

just with `\usepackage{subfig}` or generally?

2024-11-13 09:42 UTC, j95io commented
> > "center if single line, wraparound if multi line." is also the default behavior for regular figure captions, i.e. for non-table figures.
> 
> just with `\usepackage{subfig}` or generally?

generally

2025-03-23 07:37 UTC, notPlancha commented
I don't mind separating the "centre-justified" part into another pr, after checking it seems that in fact that it's centered if one line but justified (with word break enabled) when more than one line.

About the dot, should it be a function argument, should it be included in figure-supplement somehow, or should we just enforce one of them?

2025-03-25 04:27 UTC, PgBiel commented
This change appears to be consistent with the official samples here https://www.ieee.org/conferences/publishing/templates.html, so, by itself, it seems good enough.

However, I wonder if we should use the caption's [`separator`](https://typst.app//docs/reference/model/figure#definitions-caption-separator) instead, and use a set rule to have it default to `"."`, so others may change this if necessary in an expected way, without requiring a more specific knob at first.

2025-03-25 12:38 UTC, PgBiel requested changes

2025-03-25 12:38 UTC, PgBiel commented on charged-ieee/lib.typ
> +    show figure.caption: it => [#prefix~#numbers#figure.caption.separator #it.body]
Allow overriding per caption as well, not only with set rules.

```suggestion
    show figure.caption: it => [#prefix~#numbers#it.separator #it.body]
```

2025-03-25 12:38 UTC, PgBiel commented on charged-ieee/lib.typ
> +}
Please add back the newline at EOF

2025-03-25 13:18 UTC, laurmaedje commented on charged-ieee/lib.typ
> +    show figure.caption: it => [#prefix~#numbers#figure.caption.separator #it.body]
To match with the default show rule's behaviour, the trailing space should be part of the separator rather than the show rule.

2025-03-25 15:54 UTC, PgBiel commented on charged-ieee/lib.typ
> +    show figure.caption: it => [#prefix~#numbers#figure.caption.separator #it.body]
Thanks, I've updated my suggestion

2025-03-25 15:54 UTC, PgBiel commented on charged-ieee/lib.typ
> +  set figure.caption(separator: [.])
Per https://github.com/typst/templates/pull/60#discussion_r2012080121

```suggestion
  set figure.caption(separator: [. ])
```

2025-03-26 04:45 UTC, notPlancha commented
I just noticed #68, and in fact checking the template it seems that the caption of the table should be below the call.
I'll go ahead and add the suggested change

2025-03-26 14:21 UTC, PgBiel commented on charged-ieee/lib.typ
> +  show figure.where(kind: table): set figure.caption(separator: [\ ])
Let's group this up with the `show figure.where(kind: table): set figure.caption` a bit before.

2025-03-27 15:23 UTC, merged